version: "3.3"

services:
  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 8080:80

  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: scheduling_app
    volumes:
      - ../scheduling-app/offline-data/db:/var/lib/postgresql
  app:
    container_name: scheduling-app
    command: npm run dev
    build:
      context: ../scheduling-app
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
    volumes:
      - ../scheduling-app:/scheduling-app
      - node-modules-scheduling-app:/scheduling-app/node_modules
    links:
      - db:db
    expose:
      - 80
    ports:
      - 3100:80
      - 9229:9229
    environment:
      PORT: 80
      HOST: 0.0.0.0
# volumes:
#   node-modules-scheduling-app:
#   postgis-data:
